/** Comodidades/características DWV (inglês ou código) → português. Chaves normalizadas: lowercase + underscore. */
export const TRADUCOES_DWV: Record<string, string> = {
  adult_pool: 'Piscina adulto',
  intercom: 'Interfone',
  gourmet_space: 'Área gourmet',
  toys_playroom: 'Brinquedoteca',
  bar: 'Bar',
  rooftop: 'Cobertura',
  entrance_hall_decorated_and_furnished: 'Hall de entrada decorado e mobiliado',
  bike_rack: 'Bicicletário',
  lounge: 'Salão de convivência',
  sauna: 'Sauna',
  playground: 'Playground',
  gym: 'Academia',
  whirpool_in_the_pool: 'Whirlpool na piscina',
  be_social: 'Área de convivência',
  whirlpool: 'Whirlpool',
  helipad: 'Heliporto',
  elevator: 'Elevador',
  elevador: 'Elevador',
  games_room: 'Sala de jogos',
  water_reuse: 'Reuso de água',
  individual_water_light_gas_meters: 'Medidores individuais de água, luz e gás',
  entrance_to_bathers_and_beach_box: 'Acesso a banhistas e box de praia',
  solarium: 'Solário',
  party_room: 'Salão de festas',
  spa: 'Spa',
  playroom: 'Brinquedoteca',
  termic_pool: 'Piscina térmica',
  child_pool: 'Piscina infantil',
  jacuzzi: 'Jacuzzi',
  pool: 'Piscina',
  security: 'Segurança 24h',
  concierge: 'Portaria',
  garden: 'Jardim',
  barbecue: 'Churrasqueira',
  barbecue_grill: 'Churrasqueira',
  pet_area: 'Área pet',
  sports_court: 'Quadra esportiva',
  running_track: 'Pista de caminhada',
  cinema: 'Cinema',
  library: 'Biblioteca',
  coworking: 'Coworking',
  laundry: 'Lavanderia',
  valet: 'Manobrista',
  desk: 'Escritório',
  porch: 'Varanda',
  closet: 'Closet',
  hot_water_infrastructure: 'Infraestrutura para água quente',
  gas_heating: 'Aquecimento a gás',
  social_bathroom: 'Lavabo',
  lavatory: 'Lavabo',
  porcelain: 'Porcelanato',
  air_conditioning_infrastructure: 'Infraestrutura para ar-condicionado',
  dining_room: 'Sala de jantar',
  living_room: 'Sala de estar',
  living: 'Sala de estar',
  individual_water_meter: 'Medidor de água individual',
  password_lock_entrance_door: 'Porta de entrada com fechadura digital',
  kitchen: 'Cozinha',
  cozinha: 'Cozinha',
  individual_gas: 'Gás individual',
  balcony: 'Varanda',
  varanda: 'Varanda',
  workmanship_on_plaster: 'Acabamento em gesso',
  service_area: 'Área de serviço',
  internet: 'Internet',
  escritório: 'Escritório',
  área_gourmet: 'Área gourmet',
  hall_de_entrada_decorado_e_mobiliado: 'Hall de entrada decorado e mobiliado',
  salão_de_festas: 'Salão de festas',
  piscina_infantil: 'Piscina infantil',
  salão_de_convivência: 'Salão de convivência',
}

function normalizarChave(s: string): string {
  return s.trim().replace(/\s+/g, '_').replace(/-/g, '_').toLowerCase()
}

export function traduzirComodidade(raw: string): string {
  const trimmed = (raw || '').trim()
  if (!trimmed) return trimmed
  const key = normalizarChave(trimmed)
  const traducao = TRADUCOES_DWV[key]
  if (traducao) return traducao
  return trimmed.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
}
